# CircleCI pipeline for publishing to NPM
# FIXME: automate NPM publish only on origin/<branch> -> origin/master merge
version: 2
jobs:
  package:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: ./scripts/package.sh
      - store_artifacts:
          path: /scripts
      - store_artifacts:
          path: /dist
  publish:
    requires:
      - package
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - run: ./scripts/publish.sh

workflows:
  version: 2
  npm-pubish:
    jobs:
      - package
      - publish
