# CircleCI pipeline for publishing to NPM
# FIXME: automate NPM publish only on origin/<branch> -> origin/master merge
version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: chmod +x scripts/package.sh
      - run: chmod +x scripts/publish.sh
      - run: ./scripts/package.sh
      - run: ./scripts/publish.sh
